core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.routes',namespace='home')),
    path('administrator/',include('administrator.routes',namespace='admins')),
    path("users/",include("pelamar.routes",namespace="pelamar")),
]

app/pelamar/routes.py
from django.urls import path

from pelamar.controller.LamaranPageControl import ControllerLamaranPage
from pelamar.controller.ResumePageControl import ControllerResumePage
from pelamar.controller.LowonganPageControl import ControllerLowonganPage
from pelamar.controller.ReadLowonganPageControl import ControllerReadLowonganPage
from pelamar.controller.LogoutPageControl import LogoutUserController
from pelamar.controller.ReadFoto import ReadFotoController
from pelamar.controller.ReadCv import ReadCVController
from pelamar.controller.VerifyPageControl import ControllerVerifyPage

app_name = "pelamar"

urlpatterns = [
	path("myapply/",ControllerLamaranPage.as_view(),name="pelamar_apply"),
	path("resume/",ControllerResumePage.as_view(),name="pelamar_resume"),
	path("apply/",ControllerLowonganPage.as_view(),name="pelamar_lowongan"),
	path("apply/<str:slug>/",ControllerReadLowonganPage.as_view(),name="pelamar_read_lowongan"),
	path("resume/photo/<str:file>",ReadFotoController.as_view(),name="photo_pelamar"),
	path("resume/cv/<str:file>",ReadCVController.as_view(),name='cv_pelamar'),
	path("logout/",LogoutUserController.as_view(),name="logout_pelamar"),
	path("verify/",ControllerVerifyPage.as_view(),name='verify_pelamar'),
]

templates/util/dashboard_user/foot.html
{% load static %}
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'admin/plugins/common/common.min.js' %}"></script>
    <script src="{% static 'admin/js/custom.min.js' %}"></script>
    <script src="{% static 'admin/js/settings.js' %}"></script>
    <script src="{% static 'admin/js/gleek.js' %}"></script>
    <script src="{% static 'admin/js/styleSwitcher.js' %}"></script>

</body>

</html>

templates/util/dashboard_user/head.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
    <!-- Custom Stylesheet -->
    <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">

</head>
<style>

    .progress {
      list-style: none;
      display: flex;
      padding: 0;
      margin: 0;
    }
    .progress li {
      text-align: center;
      position: relative;
      flex: 1;
    }
    .progress li:not(:last-child)::after {
      content: "";
      position: absolute;
      top: 50%;
      right: -50%;
      transform: translateY(-50%);
      width: 100%;
      height: 4px;
      background: #ccc;
      z-index: -1;
    }
    .progress li.completed::after {
      background: #4CAF50;
    }
    .progress li .circle {
      width: 30px;
      height: 30px;
      background: #ccc;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      margin: 0 auto;
      font-weight: bold;
    }
    .progress li.completed .circle {
      background: #4CAF50;
    }
    .progress li .label {
      margin-top: 8px;
    }
    .containerLowongan ol{
        list-style-type: disc;
    }
    .containerLowongan li {
        list-style-type: disc;
    }
    
  </style>

<body>
{% if request.user.is_verify %}    
{% else %}
    <div class="alert alert-danger">
        Email Anda Belum Terverivikasi
        <form action="{% url 'pelamar:verify_pelamar' %}" method="POST">{%csrf_token%}
        <button style=" border: none; background: none; cursor: pointer; font-weight: bold;"> Here </button>. Klik Untuk Verifikasi Email
        </form> 
    </div>
{% endif %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-info">
            Verifikasi Sudah Terkirim, Cek Di <strong>Inbox</strong> Atau <strong>Spam</strong> Email Anda
        </div>
    {% endfor %}
{% endif %}

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'pelamar:pelamar_apply' %}">
                    <b class="logo-abbr"><img src="images/logo.png" alt=""> </b>
                    <span class="logo-compact"><img src="./images/logo-compact.png" alt=""></span>
                    <span class="brand-title">
                        <img src="images/logo-text.png" alt="">
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                <div class="header-left">
                    
                </div>
                <div class="header-right">
                    <ul class="clearfix">
                       
                        <li class="icons dropdown"><a href="javascript:void(0)" data-toggle="dropdown">
                                <i class="mdi mdi-bell-outline"></i>
                                {% if notif.count %}
                                <span style="color: #fff;" class="badge nav-text badge-pill badge-info">{{notif.count}}</span>
                                {% endif %}
                            </a>
                            <div class="drop-down animated fadeIn dropdown-menu dropdown-notfication">
                            <div class="dropdown-content-heading d-flex justify-content-between">
                                <button type="button" class="btn mb-1 btn-outline-primary btn-sm">Baca Semua</button>
                                {% if notif.count %}
                                <span class="">{{notif.count}} Notifications</span>  
                                {% else %}
                                <span style="font-size: 10px;">You Don't Have Notification</span>
                                {% endif %}

                                </div>
                                <div class="dropdown-content-body">
                                    <ul>

                                        {%  for data in notif %}
                                        <li>
                                            <a href="{% url 'pelamar:pelamar_apply' %}">
                                                <span class="mr-3 avatar-icon bg-success-lighten-2"><i class="icon-present"></i></span>
                                                <div class="notification-content">
                                                    <h6 class="notification-heading">{{data.subject}}</h6>
                                                    <span class="notification-text">
                                                    {{data.created_at|date:'U'|timedDates}} Yang Lalu
                                                </span> 
                                                </div>
                                            </a>
                                        </li>
                                        {% endfor %}
                                        
                                    </ul>
                                    
                                </div>
                            </div>
                        </li>                        
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSteItzPyeDKBxyWiOA8xrPZXIlxOYv1b1VVg&s" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile   dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <form action="{% url 'pelamar:logout_pelamar' %}" method="POST">{% csrf_token %}
                                            <button
                                            style="
                                            border:none;
                                            cursor: pointer;
                                            background: none;
                                            "
                                            >
                                                <i class="icon-key"></i> <span>Logout</span>
                                            </button>    
                                            </form>
                                            </li>                                            
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->




<!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                     <li>
                        <a href="{% url 'pelamar:pelamar_apply' %}"  aria-expanded="false">
                            <i class="icon-note menu-icon"></i>
                            <span class="nav-text">Lamaran Saya</span>
                            {% if apply.count %}
                             <span style="color: #fff;" class="badge nav-text badge-pill badge-info">{{apply.count}}</span>
                            {% endif %}
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'pelamar:pelamar_resume' %}"  aria-expanded="false">
                            <i class="icon-user menu-icon"></i><span class="nav-text">Resume</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'pelamar:pelamar_lowongan' %}" aria-expanded="false">
                            <i class="ti-search menu-icon"></i><span class="nav-text">Cari Lowongan</span>
                        </a>
                    </li>
                     <li>
                        <a href="widgets.html" aria-expanded="false">
                            <i class="icon-settings menu-icon"></i><span class="nav-text">Settings</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->