core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.routes',namespace='home')),
    path('administrator/',include('administrator.routes',namespace='admins')),
    path("users/",include("pelamar.routes",namespace="pelamar")),
]

app/administrator/routes.py
from django.urls import path

from administrator.controller.IndexPageControl import ControllerIndexPage
from administrator.controller.BuatPageControl import ControllerBuatPage
from administrator.controller.DataLowonganPageControl import ControllerDataLowonganPage
from administrator.controller.DataLamaranPageControl import ControllerDataLamaranPage
from administrator.controller.DataPelamarPageControl import ControllerDataPelamarPage
from administrator.controller.DataInterviewPageControl import ControllerDataInterviewPage
from administrator.controller.BuatKategoriPageControl import ControllerBuatKategoriPage
from administrator.controller.BuatLocationPageControl import ControllerBuatLocationPage
from administrator.controller.BuatEducationPageControl import ControllerBuatEducationPage
from administrator.controller.SettingsPageControl import ControllerSettingsPage
from administrator.controller.BuatTipePageControl import ControllerBuatTipePage
from administrator.controller.FileResponPageControl import ControllerReadCv, ControllerReadPhoto,ControllerReadFileCompany
from administrator.controller.LogoutPageControl import ControllerLogoutPage
app_name = "admins"

urlpatterns = [
	path('',ControllerIndexPage.as_view(),name='admin_index'),
	path('createlowongan/',ControllerBuatPage.as_view(),name='admin_create'),
	path('datalowongan/',ControllerDataLowonganPage.as_view(),name='admin_data_lowongan'),
	path('datalamaran/',ControllerDataLamaranPage.as_view(),name='admin_data_lamaran'),
	path('profile/<str:slug>/',ControllerDataPelamarPage.as_view(),name='admin_profile_pelamar'),
	path('iterview/',ControllerDataInterviewPage.as_view(),name='admin_data_interview'),
	path('kategori/',ControllerBuatKategoriPage.as_view(),name='admin_create_kategori'),
	path('location/',ControllerBuatLocationPage.as_view(),name='admin_create_location'),
	path('education/',ControllerBuatEducationPage.as_view(),name='admin_create_education'),
	path('tipelowongan/',ControllerBuatTipePage.as_view(),name='admin_create_tipe'),
	path('settings/',ControllerSettingsPage.as_view(),name='admin_settings'),
	path("cv/<str:file>",ControllerReadCv.as_view(),name="cv_pelamar"),
	path("photo/<str:file>",ControllerReadPhoto.as_view(),name='photo_pelamar'),
	path('file/<str:file>',ControllerReadFileCompany.as_view(),name='file_perusahaan'),
	path('logout/',ControllerLogoutPage.as_view(),name='logout_admin'),
]

templates/util/dashboard_admin/foot.html
{% load static %}

    <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'admin/plugins/common/common.min.js' %}"></script>
    <script src="{% static 'admin/js/custom.min.js' %}"></script>
    <script src="{% static 'admin/js/settings.js' %}"></script>
    <script src="{% static 'admin/js/gleek.js' %}"></script>
    <script src="{% static 'admin/js/styleSwitcher.js' %}"></script>

</body>

</html>

templates/util/dashboard_admin/head.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
    <!-- Custom Stylesheet -->
    <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'admin/plugins/tables/css/datatable/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet">

</head>
<style>

    .progress {
      list-style: none;
      display: flex;
      padding: 0;
      margin: 0;
    }
    .progress li {
      text-align: center;
      position: relative;
      flex: 1;
    }
    .progress li:not(:last-child)::after {
      content: "";
      position: absolute;
      top: 50%;
      right: -50%;
      transform: translateY(-50%);
      width: 100%;
      height: 4px;
      background: #ccc;
      z-index: -1;
    }
    .progress li.completed::after {
      background: #4CAF50;
    }
    .progress li .circle {
      width: 30px;
      height: 30px;
      background: #ccc;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      margin: 0 auto;
      font-weight: bold;
    }
    .progress li.completed .circle {
      background: #4CAF50;
    }
    .progress li .label {
      margin-top: 8px;
    }
  </style>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'admins:admin_index' %}">
                    <b class="logo-abbr"><img src="{% static 'admin/images/logo.png' %}" alt=""> 
                    </b>
                    <span class="logo-compact"><img src="{% static 'admin/images/logo-compact.png' %}" alt=""></span>
                    <span class="brand-title">
                        <img src="{% static 'admin/images/logo-text.png' %}" alt="">
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                <div class="header-left">
                    
                </div>
                <div class="header-right">
                    <ul class="clearfix">
                                                               
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSteItzPyeDKBxyWiOA8xrPZXIlxOYv1b1VVg&s" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile   dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>    
                                        <li>
                                          <form action="{% url 'admins:logout_admin' %}" method="POST">{% csrf_token %}
                                            <button
                                            style="
                                            border:none;
                                            cursor: pointer;
                                            background: none;
                                            "
                                            >
                                                <i class="icon-key"></i> <span>Logout</span>
                                            </button>    
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->





        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                     <li>
                        <a href="{% url 'admins:admin_create' %}"  aria-expanded="false">
                            <i class="icon-note menu-icon"></i><span class="nav-text">Buat Lowongan</span>
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'admins:admin_data_lamaran' %}"  aria-expanded="false">
                            <i class="icon-user menu-icon"></i><span class="nav-text">Lamaran</span>
                            {% if notifLowongan.count %}
                            <span style="color: #fff;" class="badge nav-text badge-pill badge-info">{{notifLowongan.count}}</span>
                            {% endif %}
                        </a>

                    </li>
                    <li class="">
                        <a href="{% url 'admins:admin_create_kategori' %}" class="">
                        <i class="ti-pin-alt menu-icon"></i><span class="nav-text">Kategori Lowongan</span></a>
                    </li>
                    <li class="">
                        <a href="{% url 'admins:admin_create_location' %}" class="">
                        <i class="ti-map menu-icon"></i><span class="nav-text">Location Lowongan</span></a>
                    </li>
                    <li class="">
                        <a href="{% url 'admins:admin_create_education' %}" class="">
                        <i class="ti-medall-alt menu-icon"></i><span class="nav-text">Education Lowongan</span></a>
                    </li>
                    <li>
                      <a href="{% url 'admins:admin_create_tipe' %}">
                        <i class="ti-briefcase menu-icon"></i><span class="nav-text">Type Lowongan</span>
                      </a>
                    </li>
                     <li>
                        <a href="{% url 'admins:admin_data_lowongan' %}" aria-expanded="false">
                            <i class="icon-bell menu-icon"></i><span class="nav-text">Data Lowongan</span>
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'admins:admin_data_interview' %}" aria-expanded="false">
                            <i class="ti-briefcase menu-icon"></i><span class="nav-text">Data Interview</span>
                             {% if notifInterview.count %}
                            <span style="color: #fff;" class="badge nav-text badge-pill badge-info">{{notifInterview.count}}</span>
                            {% endif %}
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'admins:admin_settings' %}" aria-expanded="false">
                            <i class="icon-settings menu-icon"></i><span class="nav-text">Settings</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->