core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.routes',namespace='home')),
    path('administrator/',include('administrator.routes',namespace='admins')),
    path("users/",include("pelamar.routes",namespace="pelamar")),
]

app/homepage/models.py
from django.db import models

# Create your models here.

app/homepage/unit/forms/forms.py
from django import forms
from django.contrib.auth.hashers import make_password

from db.models import Pengguna

class RegisterForm(forms.ModelForm):
	class Meta:
		model = Pengguna
		fields = ['username','email','password']
		error_messages = {
			'username':{
				'required': ("Username Wajib Di Isi"),
				"unique": ("Username Sudah Terpakai")
			},
			"email":{
				"unique":("Email Sudah Terdaftar"),
				"required":("Email Wajib Di Isi")
			},
			"password":{
				"required":("Password Wajib Di Isi")
			}
		}


	def clean_password(self):
		password = self.cleaned_data.get("password")
		enkripPassword = make_password(password)
		return enkripPassword

app/homepage/routes.py
from django.urls import path
from homepage.controller.HomePageControl import ControllerHomePage
from homepage.controller.ListLowonganPageControl import LowonganListControl
from homepage.controller.DetailLowonganPageControl import ControllerDetailPage
from homepage.controller.LoginPageControl import ControllerLoginPage
from homepage.controller.RegisterPageControl import ControllerRegisPage
from homepage.controller.ChangePasswordPage import ControllerChangePasswordPage
from homepage.controller.OtpPageControl import ControllerOTPPage
from homepage.controller.VerifyAnonymPageControl import ControllerVerifyAnonymPage
app_name = "home"

urlpatterns = [
	path('',ControllerHomePage.as_view(),name='halaman_utama'),
	path('lowongan/',LowonganListControl.as_view(),name='list_halaman'),
	path('detail/<str:slug>/',ControllerDetailPage.as_view(),name='detail_halaman'),
	path('login/',ControllerLoginPage.as_view(),name='login_halaman'),
	path("register/",ControllerRegisPage.as_view(),name='register_halaman'),
	path("change/password/",ControllerChangePasswordPage.as_view(),name='change_password_halaman'),
	path('verify/',ControllerOTPPage.as_view(),name='verify_otp'),
	path('account/verify/',ControllerVerifyAnonymPage.as_view(),name='verify_accounts'),
]

app/homepage/views.py
# Create your views here.

app/pelamar/routes.py
from django.urls import path

from pelamar.controller.LamaranPageControl import ControllerLamaranPage
from pelamar.controller.ResumePageControl import ControllerResumePage
from pelamar.controller.LowonganPageControl import ControllerLowonganPage
from pelamar.controller.ReadLowonganPageControl import ControllerReadLowonganPage
from pelamar.controller.LogoutPageControl import LogoutUserController
from pelamar.controller.ReadFoto import ReadFotoController
from pelamar.controller.ReadCv import ReadCVController
from pelamar.controller.VerifyPageControl import ControllerVerifyPage

app_name = "pelamar"

urlpatterns = [
	path("myapply/",ControllerLamaranPage.as_view(),name="pelamar_apply"),
	path("resume/",ControllerResumePage.as_view(),name="pelamar_resume"),
	path("apply/",ControllerLowonganPage.as_view(),name="pelamar_lowongan"),
	path("apply/<str:slug>/",ControllerReadLowonganPage.as_view(),name="pelamar_read_lowongan"),
	path("resume/photo/<str:file>",ReadFotoController.as_view(),name="photo_pelamar"),
	path("resume/cv/<str:file>",ReadCVController.as_view(),name='cv_pelamar'),
	path("logout/",LogoutUserController.as_view(),name="logout_pelamar"),
	path("verify/",ControllerVerifyPage.as_view(),name='verify_pelamar'),
]

templates/homepage/detail_lowongan.html
{% load static %}
{% load custom_filters %}
{% include 'util/homepage/head_list.html' %}

 <main>

        <!-- Hero Area Start-->
        <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background="assets/img/hero/about.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>{{detail.category.name}}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <!-- Hero Area End -->
        <!-- job post company Start -->
        <div class="job-post-company pt-120 pb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <!-- Left Content -->
                    <div class="col-xl-7 col-lg-8">
                        <!-- job single -->
                        <div class="single-job-items mb-50">
                            <div class="job-items">
                                <div class="company-img company-img-details">
                                    <a href="#"><img src="assets/img/icon/job-list1.png" alt=""></a>
                                </div>
                                <div class="job-tittle">
                                    <a href="#">
                                        <h4>{{detail.title}}</h4>
                                    </a>
                                    <ul>
                                        <li>{{detail.category.name}}</li>
                                        <li><i class="fas fa-map-marker-alt"></i>{{detail.location}}</li>
                                        {% if detail.is_salary %}
                                        <li>Gaji Tidak Di Tampilkan</li>
                                        {% else %}
                                        <li>Rp. {{detail.salary | rupiah}}</li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                          <!-- job single End -->
                       
                        <div class="job-post-details">
                            <div class="post-details1 mb-50">
                                
                                {% autoescape off %} 
                                {{detail.description}}
                                {% endautoescape %}
                            </div>
                        </div>

                    </div>
                    <!-- Right Content -->
                    <div class="col-xl-4 col-lg-4">
                        <div class="post-details3  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Job Overview</h4>
                           </div>
                          <ul>
                              <li>{{detail.updated_at |date:'U'|timedDates}} Yang Lalu<i class="fas fa-calendar"></i></li>
                              <li> {{detail.location.name}}<i class="fas fa-map-marker-alt"></i></li>
                               <li>{{detail.tipe.name}}<i class="fas fa-briefcase"> </i></li> 
                              <li>Rp. {{detail.salary | rupiah}}<i class="fas fa-dollar-sign"></i></li>
                          </ul>

                         <div class="apply-btn2">
                            {% if request.user.is_authenticated %}
                                {% if request.user.is_admin %}
                                {% else %}
                                <a href="{% url 'pelamar:pelamar_read_lowongan' slug=detail.slug %}" class="btn">Apply Now</a>
                                {% endif %}
                            {% else %}

                            {% endif %}
                         </div>
                       </div>
                        <div class="post-details4  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Company Information</h4>
                           </div>
                              <span>{{profileP.name}}</span>
                              <p>{{profileP.slogan}}</p>
                            <ul>
                                <li>Name: <span>{{profileP.name}} </span></li>
                                <li>Web : <span> {{profileP.web}}</span></li>
                                <li>Email: <span>{{profileP.email}}</span></li>
                            </ul>
                       </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- job post company End -->

    </main>

{% include 'util/homepage/foot_homepage.html' %}

templates/homepage/index.html
{% load static %}
{% load custom_filters %}
{% include 'util/homepage/head_homepage.html' %}

  <!-- Our Services Start -->
        <div class="our-services section-pad-t30">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <h2> Kategori Pekerjaan</h2>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-contnet-center">

                    
                   {% for data in kategori %}
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-cms"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">{{data.name}}</a></h5>
                                <span>({{data.id|countKategori}})</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                   
                </div>
                <!-- More Btn -->
                <!-- Section Button -->
                

            </div>
        </div>
        <!-- Our Services End -->
       
        <!-- Featured_job_start -->
        <section class="featured-job-area feature-padding" style="margin-top: -250px;">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <h2>Lowongan Pekerjaan</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                        {% for data in lowongan %}
                        <!-- single-job-content -->
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="company-img">
                                    <a href="{% url 'home:detail_halaman' slug=data.slug %}">
                                    	<img src="{% static 'homepage/assets/img/icon/job-li' %}st1.png" alt="">
                                    </a>
                                </div>
                                <div class="job-tittle">
                                    <a href="{% url 'home:detail_halaman' slug=data.slug %}"><h4>{{data.title}}</h4></a>
                                    <ul>
                                        <li>Creative Agency</li>
                                        <li><i class="fas fa-map-marker-alt"></i>{{data.location.name}}</li>
                                        <li>{{data.updated_at |date:'U'|timedDates}} Yang Lalu</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="items-link f-right">
                                <a href="{% url 'home:detail_halaman' slug=data.slug %}">Apply</a>
                            </div>
                        </div>
                        {% endfor %}
                       
                    </div>
                    <div class="row">
                    <div class="col-lg-12">
                        <div class="browse-btn2 text-center mt-50">
                            <a href="{% url 'home:list_halaman' %}" class="border-btn2">Cari Yang Lainya</a>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </section>
        <!-- Featured_job_end -->
        <!-- How  Apply Process Start-->
        <div class="apply-process-area apply-bg pt-150 pb-150" data-background="assets/img/gallery/how-applybg.png">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle white-text text-center">
                            <h2> Proses Perekrutan</h2>
                        </div>
                    </div>
                </div>
                <!-- Apply Process Caption -->
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="single-process text-center mb-30">
                            <div class="process-ion">
                                <span class="flaticon-search"></span>
                            </div>
                            <div class="process-cap">
                               <h5>1. Mecari Lowongan</h5>
                               <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-process text-center mb-30">
                            <div class="process-ion">
                                <span class="flaticon-curriculum-vitae"></span>
                            </div>
                            <div class="process-cap">
                               <h5>2. Apply Lowongan</h5>
                               <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-process text-center mb-30">
                            <div class="process-ion">
                                <span class="flaticon-tour"></span>
                            </div>
                            <div class="process-cap">
                               <h5>3. Panggilan Interview</h5>
                               <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                            </div>
                        </div>
                    </div>
                </div>
             </div>
        </div>
        <!-- How  Apply Process End-->
       
         <!-- Support Company Start-->
         <div class="support-company-area support-padding fix mb-80">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-6">
                        <div class="right-caption">
                            <!-- Section Tittle -->
                            <div class="section-tittle section-tittle2">
                                <span>Apa Yang Kita Lakukan ?</span>
                                <h2>Mencari Talenta-Talenta Yang Berkualitas</h2>
                            </div>
                            <div class="support-caption">
                                <p class="pera-top">Mollit anim laborum duis au dolor in voluptate velit ess cillum dolore eu lore dsu quality mollit anim laborumuis au dolor in voluptate velit cillum.</p>
                                <p>Mollit anim laborum.Duis aute irufg dhjkolohr in re voluptate velit esscillumlore eu quife nrulla parihatur. Excghcepteur signjnt occa cupidatat non inulpadeserunt mollit aboru. temnthp incididbnt ut labore mollit anim laborum suis aute.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6">
                        <div class="support-location-img">
                            <img src="{% static 'homepage/assets/img/service/support-img.jpg' %}" alt="">
                            <div class="support-img-cap text-center">
                                <p>Since</p>
                                <span>1994</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Support Company End-->
       

    </main>


{% include 'util/homepage/foot_homepage.html' %}

templates/homepage/list_lowongan.html
{% load static %}
{% load custom_filters %}
{% include 'util/homepage/head_list.html' %}
<main>

        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background="{% static 'homepage/assets/img/hero/about.jpg' %}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Get your job</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End -->
        <!-- Job List Area Start -->
        <div class="job-listing-area pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <!-- Left content -->
                    <div class="col-xl-3 col-lg-3 col-md-4">
                        <div class="row">
                            <div class="col-12">
                                    <div class="small-section-tittle2 mb-45">
                                    <div class="ion"> <svg 
                                        xmlns="http://www.w3.org/2000/svg"
                                        xmlns:xlink="http://www.w3.org/1999/xlink"
                                        width="20px" height="12px">
                                    <path fill-rule="evenodd"  fill="rgb(27, 207, 107)"
                                        d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z"/>
                                    </svg>
                                    </div>
                                    <h4>Filter Jobs</h4>
                                </div>
                            </div>
                        </div>
                        <!-- Job Category Listing start -->
                        <div class="job-category-listing mb-50">
                            <!-- single one -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Category</h4>
                               </div>
                               <form>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select name="kategori">
                                        <option value=""> Pilih Kategori</option>
                                        {% for data in kategori %}
                                        <option 
                                        {% if request.GET.kategori == data.name %}
                                        selected 
                                        {% endif %}
                                        value="{{data.name}}">{{data.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Job Type</h4>
                                    </div>
                                    <div class="select-job-items2">
                                    {% for data in tipe %}
                                    <select name="tipe">
                                        <option value=""> Pilih Tipe Lowongan</option>
                                        {% for data in tipe %}
                                        <option 
                                        {% if request.GET.tipe == data.name %}
                                        selected 
                                        {% endif %}
                                        value="{{data.name}}">{{data.name}}</option>
                                        {% endfor %}
                                    </select>
                                    {% endfor %}
                                    </div>
                                </div>
                                <br>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single two -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Location</h4>
                               </div>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select name="location">
                                        <option value=""> Pilih Lokasi</option>
                                        {% for data in location %}
                                        <option 
                                        {% if request.GET.location == data.name %}
                                        selected 
                                        {% endif %}
                                        value="{{data.name}}">{{data.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-50">
                                   <div class="small-section-tittle">
                                       <button type="submit" 
                                       style="
                                       border: none;
                                       cursor: pointer;
                                       width: 50%;
                                       height: 25%;
                                       background-color:#fb246a ;
                                       ">Filter</button>
                                    </form>
                                   </div>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single three -->
                            <div class="single-listing">
                                
                            </div>
                            <div class="single-listing">
                                <!-- Range Slider Start -->
                                <aside class="left_widgets p_filter_widgets price_rangs_aside sidebar_box_shadow">
                                    
                                </aside>
                              <!-- Range Slider End -->
                            </div>
                        </div>
                        <!-- Job Category Listing End -->
                    </div>
                    <!-- Right content -->
                    <div class="col-xl-9 col-lg-9 col-md-8">
                        <!-- Featured_job_start -->
                        <section class="featured-job-area">
                            <div class="container">
                                <!-- Count of Job list Start -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="count-job mb-35">                                           
                                            <span>{{lowongan.count}} Lowongan Tersedia</span>
                                            <!-- Select job items start -->
                                           
                                            <!--  Select job items End-->
                                        </div>
                                    </div>
                                </div>
                                <!-- Count of Job list End -->
                                 {% for data in lowongan %}
                        <!-- single-job-content -->
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="company-img">
                                    <a href="{% url 'home:detail_halaman' slug=data.slug %}">
                                        <img src="{% static 'homepage/assets/img/icon/job-li' %}st1.png" alt="">
                                    </a>
                                </div>
                                <div class="job-tittle">
                                    <a href="{% url 'home:detail_halaman' slug=data.slug %}"><h4>{{data.title}}</h4></a>
                                    <ul>
                                        <li>{{data.category.name}}</li>
                                        <li><i class="fas fa-map-marker-alt"></i>{{data.location.name}}</li>
                                        <li>{{data.updated_at |date:'U'|timedDates}} Yang Lalu</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                            </div>
                        </section>
                        <!-- Featured_job_end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Job List Area End -->
        <!--Pagination Start  -->
        <div class="pagination-area pb-115 text-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="single-wrap d-flex justify-content-center">
                            <!-- <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-start">
                                    <li class="page-item active"><a class="page-link" href="#">01</a></li>
                                    <li class="page-item"><a class="page-link" href="#">02</a></li>
                                    <li class="page-item"><a class="page-link" href="#">03</a></li>
                                <li class="page-item"><a class="page-link" href="#"><span class="ti-angle-right"></span></a></li>
                                </ul>
                            </nav> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Pagination End  -->
        
    </main>

{% include 'util/homepage/foot_homepage.html' %}

templates/homepage/login.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
         <title>Login Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
</head>
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #fb246a;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: blue;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #fb246a; /* fallback for old browsers */
  background: #fb246a;
  background: #fb246a;
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}
</style>
<body>
<div class="login-page">
  <div class="form">
    {% if messages %}
    {% for message in messages %}
      <span style="color:red;font-size: 15px;">* {{message}}</span>
    {% endfor %}  
    {% endif %}
     <form style="margin-top:10px;" class="login-form" action="" method="POST">{% csrf_token %}
      <input type="email" name="email" placeholder="Your Email"/>
      <input type="password" name="password" placeholder="Your Password"/>
      <button>login</button>
      <p class="message">Not registered? <a href="{% url 'home:register_halaman' %}">Create an account</a></p>
    </form>
  </div>
</div>
<script>

</script>
</body>
</html>