core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.routes',namespace='home')),
    path('administrator/',include('administrator.routes',namespace='admins')),
    path("users/",include("pelamar.routes",namespace="pelamar")),
]

app/homepage/models.py
from django.db import models

# Create your models here.

app/homepage/unit/forms/forms.py
from django import forms
from django.contrib.auth.hashers import make_password

from db.models import Pengguna

class RegisterForm(forms.ModelForm):
	class Meta:
		model = Pengguna
		fields = ['username','email','password']
		error_messages = {
			'username':{
				'required': ("Username Wajib Di Isi"),
				"unique": ("Username Sudah Terpakai")
			},
			"email":{
				"unique":("Email Sudah Terdaftar"),
				"required":("Email Wajib Di Isi")
			},
			"password":{
				"required":("Password Wajib Di Isi")
			}
		}


	def clean_password(self):
		password = self.cleaned_data.get("password")
		enkripPassword = make_password(password)
		return enkripPassword

app/administrator/routes.py
from django.urls import path

from administrator.controller.IndexPageControl import ControllerIndexPage
from administrator.controller.BuatPageControl import ControllerBuatPage
from administrator.controller.DataLowonganPageControl import ControllerDataLowonganPage
from administrator.controller.DataLamaranPageControl import ControllerDataLamaranPage
from administrator.controller.DataPelamarPageControl import ControllerDataPelamarPage
from administrator.controller.DataInterviewPageControl import ControllerDataInterviewPage
from administrator.controller.BuatKategoriPageControl import ControllerBuatKategoriPage
from administrator.controller.BuatLocationPageControl import ControllerBuatLocationPage
from administrator.controller.BuatEducationPageControl import ControllerBuatEducationPage
from administrator.controller.SettingsPageControl import ControllerSettingsPage
from administrator.controller.BuatTipePageControl import ControllerBuatTipePage
from administrator.controller.FileResponPageControl import ControllerReadCv, ControllerReadPhoto,ControllerReadFileCompany
from administrator.controller.LogoutPageControl import ControllerLogoutPage
app_name = "admins"

urlpatterns = [
	path('',ControllerIndexPage.as_view(),name='admin_index'),
	path('createlowongan/',ControllerBuatPage.as_view(),name='admin_create'),
	path('datalowongan/',ControllerDataLowonganPage.as_view(),name='admin_data_lowongan'),
	path('datalamaran/',ControllerDataLamaranPage.as_view(),name='admin_data_lamaran'),
	path('profile/<str:slug>/',ControllerDataPelamarPage.as_view(),name='admin_profile_pelamar'),
	path('iterview/',ControllerDataInterviewPage.as_view(),name='admin_data_interview'),
	path('kategori/',ControllerBuatKategoriPage.as_view(),name='admin_create_kategori'),
	path('location/',ControllerBuatLocationPage.as_view(),name='admin_create_location'),
	path('education/',ControllerBuatEducationPage.as_view(),name='admin_create_education'),
	path('tipelowongan/',ControllerBuatTipePage.as_view(),name='admin_create_tipe'),
	path('settings/',ControllerSettingsPage.as_view(),name='admin_settings'),
	path("cv/<str:file>",ControllerReadCv.as_view(),name="cv_pelamar"),
	path("photo/<str:file>",ControllerReadPhoto.as_view(),name='photo_pelamar'),
	path('file/<str:file>',ControllerReadFileCompany.as_view(),name='file_perusahaan'),
	path('logout/',ControllerLogoutPage.as_view(),name='logout_admin'),
]

app/homepage/routes.py
from django.urls import path
from homepage.controller.HomePageControl import ControllerHomePage
from homepage.controller.ListLowonganPageControl import LowonganListControl
from homepage.controller.DetailLowonganPageControl import ControllerDetailPage
from homepage.controller.LoginPageControl import ControllerLoginPage
from homepage.controller.RegisterPageControl import ControllerRegisPage
from homepage.controller.ChangePasswordPage import ControllerChangePasswordPage
from homepage.controller.OtpPageControl import ControllerOTPPage
from homepage.controller.VerifyAnonymPageControl import ControllerVerifyAnonymPage
app_name = "home"

urlpatterns = [
	path('',ControllerHomePage.as_view(),name='halaman_utama'),
	path('lowongan/',LowonganListControl.as_view(),name='list_halaman'),
	path('detail/<str:slug>/',ControllerDetailPage.as_view(),name='detail_halaman'),
	path('login/',ControllerLoginPage.as_view(),name='login_halaman'),
	path("register/",ControllerRegisPage.as_view(),name='register_halaman'),
	path("change/password/",ControllerChangePasswordPage.as_view(),name='change_password_halaman'),
	path('verify/',ControllerOTPPage.as_view(),name='verify_otp'),
	path('account/verify/',ControllerVerifyAnonymPage.as_view(),name='verify_accounts'),
]

app/homepage/views.py
# Create your views here.

app/pelamar/routes.py
from django.urls import path

from pelamar.controller.LamaranPageControl import ControllerLamaranPage
from pelamar.controller.ResumePageControl import ControllerResumePage
from pelamar.controller.LowonganPageControl import ControllerLowonganPage
from pelamar.controller.ReadLowonganPageControl import ControllerReadLowonganPage
from pelamar.controller.LogoutPageControl import LogoutUserController
from pelamar.controller.ReadFoto import ReadFotoController
from pelamar.controller.ReadCv import ReadCVController
from pelamar.controller.VerifyPageControl import ControllerVerifyPage

app_name = "pelamar"

urlpatterns = [
	path("myapply/",ControllerLamaranPage.as_view(),name="pelamar_apply"),
	path("resume/",ControllerResumePage.as_view(),name="pelamar_resume"),
	path("apply/",ControllerLowonganPage.as_view(),name="pelamar_lowongan"),
	path("apply/<str:slug>/",ControllerReadLowonganPage.as_view(),name="pelamar_read_lowongan"),
	path("resume/photo/<str:file>",ReadFotoController.as_view(),name="photo_pelamar"),
	path("resume/cv/<str:file>",ReadCVController.as_view(),name='cv_pelamar'),
	path("logout/",LogoutUserController.as_view(),name="logout_pelamar"),
	path("verify/",ControllerVerifyPage.as_view(),name='verify_pelamar'),
]

templates/util/homepage/foot_homepage.html
{% load static %}
        <!-- footer-bottom area -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                     <div class="row d-flex justify-content-between align-items-center">
                         <div class="col-xl-10 col-lg-10 ">
                             <div class="footer-copy-right">
                                 <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                             </div>
                         </div>
                         <div class="col-xl-2 col-lg-2">
                             <div class="footer-social f-right">
                                 <a href="#"><i class="fab fa-facebook-f"></i></a>
                                 <a href="#"><i class="fab fa-twitter"></i></a>
                                 <a href="#"><i class="fas fa-globe"></i></a>
                                 <a href="#"><i class="fab fa-behance"></i></a>
                             </div>
                         </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>

  <!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'homepage/assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'homepage/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/popper.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'homepage/assets/js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'homepage/assets/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/slick.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/price_rangs.js' %}"></script>
        
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'homepage/assets/js/wow.min.js' %}"></script>
		<script src="{% static 'homepage/assets/js/animated.headline.js' %}"></script>
        <script src="{% static 'homepage/assets/js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'homepage/assets/js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'homepage/assets/js/jquery.sticky.js' %}"></script>
        
        <!-- contact js -->
        <script src="{% static 'homepage/assets/js/contact.js' %}"></script>
        <script src="{% static 'homepage/assets/js/jquery.form.js' %}"></script>
        <script src="{% static 'homepage/assets/js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'homepage/assets/js/mail-script.js' %}"></script>
        <script src="{% static 'homepage/assets/js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'homepage/assets/js/plugins.js' %}"></script>
        <script src="{% static 'homepage/assets/js/main.js' %}"></script>
        
    </body>
</html>

templates/util/homepage/head_homepage.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
         <title>Job board HTML-5 Template </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'homepage/assets/img/favicon.ico' %}">

		<!-- CSS here -->
            <link rel="stylesheet" href="{% static 'homepage/assets/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/price_rangs.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/style.css' %}">
   </head>

   <body>
    <!-- Preloader Start -->
    <!-- <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'homepage/assets/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div> -->
    <!-- Preloader Start -->
     <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <h2>PT. MCS</h2>
                            </div>  
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="index.html">Home</a></li>
                                            <li><a href="job_listing.html">Cari Lowongan </a></li>
                                            <li><a href="about.html">Tentang</a></li>
                                            <li><a href="#">Page</a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">Blog</a></li>
                                                    <li><a href="single-blog.html">Blog Details</a></li>
                                                    <li><a href="elements.html">Elements</a></li>
                                                    <li><a href="job_details.html">job Details</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                            <li class="d-block d-lg-none">
                                                <a href="#">Login / Register</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>          
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                    <a href="#" class="btn head-btn1">Register</a>
                                    <a href="#" class="btn head-btn2">Login</a>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>
    <main>

        <!-- slider Area Start-->
        <div class="slider-area ">
            <!-- Mobile Menu -->
            <div class="slider-active">
                <div class="single-slider slider-height d-flex align-items-center" 
                data-background="{% static 'homepage/assets/img/hero/h1_hero.jpg' %}">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-9 col-md-10">
                                <div class="hero__caption">
                                    <h1>Mari Tumbuh dan Sukses Bersama Kami!</h1>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- slider Area End-->

templates/util/homepage/head_list.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
         <title>Job board HTML-5 Template </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'homepage/assets/img/favicon.ico' %}">

		<!-- CSS here -->
            <link rel="stylesheet" href="{% static 'homepage/assets/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/price_rangs.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'homepage/assets/css/style.css' %}">
   </head>
   <style>
    ol, li {
    list-style: decimal; /* untuk ordered list */
    }
    ul, li {
        list-style: disc; /* untuk unordered list */
    }
   </style>
   <body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'homepage/assets/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
     <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <h2>PT. MCS</h2>
                            </div>  
                        </div>
                        {% include 'util/homepage/navbar.html' %}
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>

templates/util/homepage/navbar.html
{% load static %}
<div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="/">Home</a></li>
                                            <li><a href="{% url 'home:list_halaman' %}">Cari Lowongan </a></li>
                                            <li><a href="about.html">Tentang</a></li>                                            
                                            <li><a href="contact.html">Contact</a></li>
                                            {% if request.user.is_authenticated %}
                                                {% if request.user.is_admin %}
                                                <li class="d-block d-lg-none">
                                                    <a href="{% url 'admins:admin_index' %}">Dashboard</a>
                                                </li>
                                                {% else %}
                                                 <li class="d-block d-lg-none">
                                                    <a href="{% url 'pelamar:pelamar_apply' %}">Dashboard</a>
                                                </li>
                                                {% endif %}

                                            {% else %}
                                            <li class="d-block d-lg-none">
                                                <a href="{% url 'home:login_halaman' %}">Login / Register</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>          
                                <!-- Header-btn -->
                                {% if request.user.is_authenticated %}
                                <div class="header-btn d-none f-right d-lg-block">
                                    {% if request.user.is_admin %}
                                    <a href="{% url 'admins:admin_index' %}" class="btn">Dashboard</a>
                                    {% else %}
                                    <a href="{% url 'pelamar:pelamar_apply' %}" class="btn">Dashboard</a>
                                    {% endif %}
                                </div>
                                {% else %}
                                <div class="header-btn d-none f-right d-lg-block">
                                    <a href="{% url 'home:register_halaman' %}" class="btn head-btn1">Register</a>
                                    <a href="{% url 'home:login_halaman' %}" class="btn head-btn2">Login</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>